server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://root:123@localhost:27017/admin
      database: xc_cms
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
xuecheng:
  mq:
#    queue: queue_cms_postpage_03 # cms 客户端监控的队列名称（不同的客户端监控的队列不能重复）
    queue: queue_cms_postpage_03
#    routingKey: 5a751fab6abb5044e0d19ea1 # 此routingKey为门户站点ID
    routingKey: 5f5c7e69c84bc83ae8e1721f # 此routingKey为课程详情站点ID
# 值与 D:\AllWorkspace\webstormws\xczx\XcEduCode\xc-service-manage-course\src\main\resources\application.yml course-publish.siteId相等